### PR TITLE
chore: fix fmt

### PR DESCRIPTION
**Pull request by ilyar**
https://github.com/ever-guild/ever-solidity/actions/runs/4474729055

### CODE REVIEW

**Comment by ilyar** [comment]
@BorisI up

**Review by cryshado — CHANGES_REQUESTED** [review]
In order to review changes about code formatting, we need the configuration and/or information about the tools that were used to perform this formatting. Please provide this information if it possible. Thanks!

**Comment by ilyar** [comment]
@cryshado 

i'm do
```shell
cargo fmt --all -- --check
````
i'm fix it:

```shell
cargo fmt
````

**Comment by ilyar** [comment]
@cryshado  please see https://github.com/tonlabs/TON-Solidity-Compiler/pull/112/commits

**Pull request closed without merging**
